Select child row based on tree item, rather than tree
Select child row based on tree item, rather than tree

Before fix:

Always need to select with tree / table / list type, rather than tree item / list item / data item
>>> selectrow('*Work*tmp*', 'Namespace Tree Control', 'Test')
1
>>> selectrow('*Work*tmp*', 'Cobra_Folder_Selection_Test_2', 'Test')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\VMware\CobraWinLDTP\ldtp\__init__.py", line 390, in selectrow
    return _remote_selectrow(window_name, object_name, row_text, False)
  File "C:\Program Files (x86)\VMware\CobraWinLDTP\ldtp\client.py", line 66, in __call__
    return self.__send(self.__name, args)
  File "C:\Python27\lib\xmlrpclib.py", line 1575, in __request
    verbose=self.__verbose
  File "C:\Program Files (x86)\VMware\CobraWinLDTP\ldtp\client.py", line 184, in request
    raise LdtpExecutionError(e.faultString.encode('utf-8'))
ldtp.client_exception.LdtpExecutionError: Unable to find Object: Cobra_Folder_Selection_Test_2

After fix:

>>> selectrow('*Work*tmp*', 'Cobra_Folder_Selection_Test_2', 'Test')
1
>>> selectrow('*Work*tmp*', 'Cobra_Folder_Selection_Test_1', 'Test')
1
>>>

Credit: "Jia Liu" <jia.jl.liu@oracle.com> for reporting this issue

QA Notes:
Testing Done: Windows folder
Documentation Notes:
Bug Number:
Reviewed by:
Approved by:
Mailto: